#person:
##  name: liujun
##  age: 22
##  maps: {k1: v1,k2: v2}
##  lists:
##    -code
##    -music
##    -gril
##  birth: 1998/04/16
server:
  port: 8081
spring:
  profiles:
    active: dev
---
server:
  port: 8082
spring:
  profiles: dev
#debug: true

kuang:
  hello:
   prefix: "ppp"
   suffix: "sss"
---
server:
  port: 8083
spring:
  profiles: test

