logging:
  level:
    com.crrcdt.meeting.controller: DEBUG

spring:
  freemarker:
    request-context-attribute: request
    suffix: .ftl
    content-type: text/html
    cache: false
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///meeting?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 8081
management:
  endpoints.web.exposure.include: loggers
  endpoint.health.show-details: always
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/crrcdt/meeting/mapper/xml/*.xml
  type-aliases-package: com.crrcdt.meeting.entity